all:
   vars:
      ansible_user: mvp
      ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38373065663638616136326238373933656235316137356539636433383734366230373539636463
          3534363633326334306332353964666362316433376631370a636236346264633862623938396539
          31636265306431663263353131663233633934393065333865306463333966643833343763633134
          3638316662643635360a613631363437343738623039323334363035313138666134306462663937
          31343136666365323565393166393964623161623835356636323337386333303036
   children:
      master:
         hosts:
            master1:
               ansible_host: 100.64.0.1
         vars:
            ansible_user: mvp
